package kr.co.talk.domain.statistics.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ProductInfo")
public class ProductInfo {
	@DynamoDBHashKey // 테이블의 파티션 키 속성으로 매핑
	@DynamoDBAutoGeneratedKey // 파티션 키 속성을 자동 생성, String만 가능(UUID로 생성)
	private String id;
	
	@DynamoDBAttribute // 속성들을 DynamoDB 테이블 속성과 매핑
	private String msrp;
	
	@DynamoDBAttribute
	private String cost;
}