name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: read -d '' x | echo "${{ vars.TEST }}" && echo $x
    
